### ISSUE TITLE
Ride Sharing Example NullPointerException

### ISSUE THREAD

**Issue by cdcsl** [ververica/stateful-functions#33]
I'm running the ride sharing example on a Flink cluster (no docker) with one worker node and getting the following error after about a minute of runtime (sometimes sooner). I'm using the default rate limit and application.yaml setting for the grid, drivers, and passengers. The Flink worker has 8 slots. There are three Kafka brokers running and the topics are replicated across them.

> Sink: com.ververica.statefun.examples.ridesharing-to-driver-egress, Sink: com.ververica.statefun.examples.ridesharing-to-passenger-egress) (8/8) (adf0bdac695657a878c50dfc5efaeca2) switched from RUNNING to FAILED.
com.ververica.statefun.flink.core.functions.StatefulFunctionInvocationException: An error occurred when attempting to invoke function FunctionType(com.ververica.statefun.examples.ridesharing, driver).
	at com.ververica.statefun.flink.core.functions.StatefulFunction.receive(StatefulFunction.java:54)
	at com.ververica.statefun.flink.core.functions.ReusableContext.apply(ReusableContext.java:70)
	at com.ververica.statefun.flink.core.functions.FunctionActivation.applyNextPendingEnvelope(FunctionActivation.java:49)
	at com.ververica.statefun.flink.core.functions.LocalFunctionGroup.processNextEnvelope(LocalFunctionGroup.java:60)
	at com.ververica.statefun.flink.core.functions.Reductions.processEnvelopes(Reductions.java:143)
	at com.ververica.statefun.flink.core.functions.Reductions.apply(Reductions.java:134)
	at com.ververica.statefun.flink.core.functions.FunctionGroupOperator.processElement(FunctionGroupOperator.java:76)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$ChainingOutput.pushToOperator(OperatorChain.java:550)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$ChainingOutput.collect(OperatorChain.java:527)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$ChainingOutput.collect(OperatorChain.java:487)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:730)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:708)
	at com.ververica.statefun.flink.core.feedback.FeedbackUnionOperator.sendDownstream(FeedbackUnionOperator.java:174)
	at com.ververica.statefun.flink.core.feedback.FeedbackUnionOperator.processElement(FeedbackUnionOperator.java:78)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:173)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.processElement(StreamTaskNetworkInput.java:151)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.emitNext(StreamTaskNetworkInput.java:128)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:69)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:310)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:187)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:469)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:702)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:527)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at com.ververica.statefun.sdk.Address.<init>(Address.java:39)
	at com.ververica.statefun.sdk.Context.send(Context.java:84)
	at com.ververica.statefun.examples.ridesharing.FnDriver.whenRideHasStarted(FnDriver.java:102)
	at com.ververica.statefun.sdk.match.MatchBinder$Method.apply(MatchBinder.java:150)
	at com.ververica.statefun.sdk.match.MatchBinder.invoke(MatchBinder.java:128)
	at com.ververica.statefun.sdk.match.StatefulMatchFunction.invoke(StatefulMatchFunction.java:46)
	at com.ververica.statefun.flink.core.functions.StatefulFunction.receive(StatefulFunction.java:52)
	... 23 more

**Comment by igalshilman** [comment]
Hi @cdcsl,

This example was setup for docker, and it assumes that it starts with a fresh Kafka topic, I assume that it is not the case in your setup.
What I can see from the stack trace is that a driver function would get a ride started event without a ride request event (perhaps from a previous run of the job?).

To overcome this, try clearing the Kafka topics between the runs.

In the meantime I will create an issue to expose a "start from latest" mode for Kafka.
Hope it helps.
